"""
model_builder.py — Copy, add, and remove files to create the HSLE model tree.

ADDED files:
  - Copy ref_hsle/rel_path → output/rel_path.
  - Conflict if path already exists in new_sle AND content differs from ref_hsle.

REMOVED files:
  - Delete output/rel_path.
  - Safety check: only auto-delete if file still matches ref_sle content (unchanged
    in the new model); otherwise flag for review.
"""

import filecmp
import grp
import os
import shutil
import stat
from typing import Tuple

from .analysis_parser import FileEntry


# --------------------------------------------------------------------------- #
#  Create output tree
# --------------------------------------------------------------------------- #


# Top-level directories in a model that are compilation outputs and must never
# be copied into the converted HSLE model.
_COMPILE_OUTPUT_DIRS = frozenset({'output', '.grdlbuild_logs'})


def create_output(new_sle: str, output: str) -> None:
    """Copy the entire new SLE model to the output directory, preserving symlinks
    during the initial tree copy, then post-process to make the model fully writable.

    Compilation-output directories ('output', '.grdlbuild_logs') are excluded
    from the copy — they are regenerated by the HSLE build and must not be
    carried forward from the SLE model.

    Post-copy steps (applied in order):
    1. Replace file-symlinks with writable copies of their targets.
       shutil.copytree(symlinks=True) preserves symlinks verbatim.  When the
       build writes to a file that is actually a symlink into a shared read-only
       area the write goes through to the shared file and fails with
       PermissionError (e.g. cfg/nvlsi7_n2p.design.cfg → GK4 integration area).
       Symlinks to directories are left as-is to avoid recursive deep copies of
       shared areas; dangling symlinks are also left untouched.
    2. Ensure every non-symlink file and directory has owner write permission.
       Source models often contain read-only files (e.g. 444/555) that would
       cause PermissionError when the converter writes ADDED or MODIFIED content.
    3. Remove PCD compiled-output overrides from any PCD_WORKAREA tree so that
       gen_overrides.py does not try to push them to the read-only integration
       area at build time.
    """
    shutil.copytree(new_sle, output, symlinks=True,
                    ignore=shutil.ignore_patterns(*_COMPILE_OUTPUT_DIRS))
    _dereference_file_symlinks(output)
    _chmod_writable_tree(output)
    removed = _remove_pcd_compiled_overrides(output)
    if removed:
        print(f"  [create_output] Removed {len(removed)} PCD compiled-output "
              f"override(s) from PCD_WORKAREA (will be regenerated by build):")
        for r in removed:
            print(f"    - {r}")


# --------------------------------------------------------------------------- #
#  ADDED
# --------------------------------------------------------------------------- #

def apply_added(
    entry: FileEntry,
    *,
    ref_hsle: str,
    new_sle: str,
    output: str,
    donor: str | None = None,
    conflict_policy: str = 'manual',
    dry_run: bool = True,
) -> Tuple[str, str]:
    """
    Copy a file into output/rel_path, preferring the donor model over ref_hsle
    when the donor has the file (it is typically more up-to-date).

    Source priority: donor → ref_hsle

    Returns (outcome, detail) where outcome is one of:
      applied             — copied from ref_hsle
      applied_from_donor  — copied from donor model
      would_apply         — dry-run: would copy from ref_hsle
      would_apply_donor   — dry-run: would copy from donor
      conflict            — path exists in new model with different content
      already_same        — path exists and is already identical to chosen source
      missing_ref         — file not found in ref_hsle (and not in donor)
    """
    dst          = os.path.join(output,  entry.rel_path)
    new_sle_path = os.path.join(new_sle, entry.rel_path)

    # Resolve the best available source: donor first, then ref_hsle
    src, source_label = _resolve_source(entry.rel_path, ref_hsle=ref_hsle, donor=donor)
    if src is None:
        return ('missing_ref', f"Not found in ref_hsle or donor: {entry.rel_path}")

    # Validate paths stay inside their roots
    if not _is_under(src, source_label) or not _is_under(dst, output):
        return ('error', 'path escapes model root')

    # Conflict check — does new model already have this path?
    if os.path.exists(new_sle_path) and not os.path.islink(new_sle_path):
        if os.path.islink(src):
            tgt_src = os.readlink(src)
            tgt_new = os.readlink(new_sle_path) if os.path.islink(new_sle_path) else None
            if tgt_src == tgt_new:
                return ('already_same', f'symlink target matches ({_source_name(source_label, donor, ref_hsle)})')
        elif filecmp.cmp(new_sle_path, src, shallow=False):
            return ('already_same', f'content already identical to {_source_name(source_label, donor, ref_hsle)}')
        else:
            if conflict_policy == 'manual':
                return ('conflict', 'path exists in new model with different content (manual review)')
            # auto: overwrite — fall through to copy below

    is_donor = (donor and source_label == donor)

    if dry_run:
        return ('would_apply_donor' if is_donor else 'would_apply', '')

    os.makedirs(os.path.dirname(dst), exist_ok=True)

    if os.path.islink(src):
        link_target = os.readlink(src)
        if os.path.exists(dst) or os.path.islink(dst):
            os.unlink(dst)
        os.symlink(link_target, dst)
    else:
        shutil.copy2(src, dst)
        src_mode = os.stat(src, follow_symlinks=False).st_mode
        new_mode = os.stat(dst).st_mode | stat.S_IWUSR
        if src_mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH):
            new_mode |= stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        os.chmod(dst, new_mode)

    return ('applied_from_donor' if is_donor else 'applied', '')


# --------------------------------------------------------------------------- #
#  REMOVED
# --------------------------------------------------------------------------- #

def apply_removed(
    entry: FileEntry,
    *,
    ref_sle: str,
    output: str,
    safety_check: bool = True,
    dry_run: bool = True,
) -> Tuple[str, str]:
    """
    Delete output/rel_path.

    Returns (outcome, detail) where outcome is one of:
      removed         — deleted successfully
      would_remove    — dry-run: would delete
      already_absent  — file not present in output (may have been removed already)
      conflict        — safety check failed: file differs from ref_sle in new model
    """
    target    = os.path.join(output,  entry.rel_path)
    ref_orig  = os.path.join(ref_sle, entry.rel_path)

    if not _is_under(target, output):
        return ('error', 'path escapes output root')

    if not os.path.exists(target) and not os.path.islink(target):
        return ('already_absent', 'file not present in new model')

    if safety_check and os.path.exists(ref_orig) and not os.path.islink(target):
        # Only auto-remove if still matches the ref SLE content (unchanged in new model)
        if not filecmp.cmp(target, ref_orig, shallow=False):
            return (
                'conflict',
                'file differs from ref_sle — may have been updated in new model; verify before deleting',
            )

    if dry_run:
        return ('would_remove', '')

    if os.path.islink(target) or os.path.isfile(target):
        os.unlink(target)
    elif os.path.isdir(target):
        shutil.rmtree(target)

    return ('removed', '')


# --------------------------------------------------------------------------- #
#  Helpers
# --------------------------------------------------------------------------- #

def _is_under(path: str, root: str) -> bool:
    """Return True if path is strictly under (or equal to) root after resolution."""
    try:
        real_path = os.path.realpath(os.path.abspath(path))
        real_root = os.path.realpath(os.path.abspath(root))
        return real_path.startswith(real_root + os.sep) or real_path == real_root
    except OSError:
        return False


def _resolve_source(
    rel_path: str,
    *,
    ref_hsle: str,
    donor: str | None,
) -> tuple[str | None, str]:
    """
    Return (absolute_src_path, root_dir) for the best available source of rel_path.
    Priority: donor > ref_hsle.

    Path variations tried:
      - Exact path
      - Cdie0TlsTb -> Cdie1TlsTb substitution (when Cdie0 not in donor/ref_hsle
        but Cdie1 exists; both are equivalent for most files in py_lib_overrides)

    Returns (None, '') if no variation is found.
    """
    candidates = [rel_path]
    if 'Cdie0TlsTb' in rel_path:
        candidates.append(rel_path.replace('Cdie0TlsTb', 'Cdie1TlsTb'))

    if donor:
        for rp in candidates:
            c = os.path.join(donor, rp)
            if os.path.exists(c) or os.path.islink(c):
                return c, donor
    for rp in candidates:
        c = os.path.join(ref_hsle, rp)
        if os.path.exists(c) or os.path.islink(c):
            return c, ref_hsle
    return None, ''


def _source_name(source_root: str, donor: str | None, ref_hsle: str) -> str:
    """Human-readable label for the source root."""
    if donor and source_root == donor:
        return 'donor'
    return 'ref_hsle'


# --------------------------------------------------------------------------- #
#  Permission & ownership helpers
# --------------------------------------------------------------------------- #

def finalize_permissions(output: str, group: str = 'soc') -> list[str]:
    """Walk output tree and apply group ownership + write permissions.

    For every non-symlink file and directory under *output*:
      - Set group to *group* (e.g. 'soc') via chown.
      - Add u+w and g+w so the model is writable by owner and group members.

    Symlinks are skipped — their target permissions are not changed.

    Returns a list of warning strings for any paths where chown/chmod failed
    (logged by the caller; never raises).
    """
    try:
        gid = grp.getgrnam(group).gr_gid
    except KeyError:
        return [f"Group '{group}' not found on this system — skipping chown"]

    warnings: list[str] = []
    for root, dirs, files in os.walk(output):
        for name in dirs + files:
            p = os.path.join(root, name)
            if os.path.islink(p):
                continue
            _apply_perms(p, gid, warnings)
    # Also fix the root output directory itself
    if not os.path.islink(output):
        _apply_perms(output, gid, warnings)
    return warnings


def _apply_perms(path: str, gid: int, warnings: list[str]) -> None:
    """Set group ownership and add u+w g+w to a single path."""
    try:
        st = os.stat(path)
        if st.st_gid != gid:
            os.chown(path, -1, gid)          # -1 = keep existing uid
        new_mode = st.st_mode | stat.S_IWUSR | stat.S_IWGRP
        if stat.S_IMODE(st.st_mode) != stat.S_IMODE(new_mode):
            os.chmod(path, new_mode)
    except OSError as exc:
        warnings.append(f"{path}: {exc}")


_GK4_INTEGRATION_MARKERS = (
    os.sep + 'GK4' + os.sep + 'integrate' + os.sep,
)


def _dereference_file_symlinks(root: str) -> None:
    """Handle file-symlinks after copytree.

    shutil.copytree(symlinks=True) preserves symlinks verbatim.  Two cases
    require action:

    1. Symlinks into GK4 integration areas (read-only shared files generated
       during compilation, e.g. cfg/nvlsi7_n2p.design.cfg).  These will be
       regenerated by the HSLE build from their .mako templates — they must be
       **deleted** from the output model, not copied.

    2. All other file-symlinks pointing to regular files — replace with a
       writable copy so build scripts can open them for writing without
       following the link into a potentially read-only shared area.

    Symlinks that resolve to directories, and dangling symlinks, are left
    untouched.
    """
    for dirpath, _dirs, files in os.walk(root):
        for name in files:
            p = os.path.join(dirpath, name)
            if not os.path.islink(p):
                continue
            raw_target = os.readlink(p)
            abs_target = raw_target if os.path.isabs(raw_target) else os.path.join(dirpath, raw_target)
            real_target = os.path.realpath(abs_target)
            if not os.path.isfile(real_target):
                continue  # directory symlink or dangling — leave as-is
            # Symlinks into GK4 integration area are build-time generated
            # outputs.  Remove them so the HSLE build regenerates them fresh.
            if any(marker in abs_target for marker in _GK4_INTEGRATION_MARKERS):
                try:
                    os.unlink(p)
                except OSError:
                    pass
                continue
            # All other file-symlinks: replace with a writable copy.
            try:
                os.unlink(p)
                shutil.copy2(real_target, p)
                os.chmod(p, os.stat(p).st_mode | stat.S_IWUSR)
            except OSError:
                pass


def _chmod_writable_tree(root: str) -> None:
    """Add u+w to every non-symlink file and directory under root (including root)."""
    for dirpath, dirs, files in os.walk(root):
        for name in dirs + files:
            p = os.path.join(dirpath, name)
            if not os.path.islink(p):
                try:
                    os.chmod(p, os.stat(p).st_mode | stat.S_IWUSR)
                except OSError:
                    pass
    if not os.path.islink(root):
        try:
            os.chmod(root, os.stat(root).st_mode | stat.S_IWUSR)
        except OSError:
            pass


# Marker that identifies the PCD workarea override directory in a model tree.
_PCD_WORKAREA = os.sep + 'PCD_WORKAREA' + os.sep

# Path fragment inside PCD_WORKAREA that identifies a PCD compiled-output file
# (as opposed to a hand-edited source override).  gen_overrides.py would try to
# push these to the integration area, which is owned by a different user and is
# read-only, causing PermissionError at build time.
_PCD_COMPILED_OUTPUT_MARKER = 'pchlp' + os.sep + 'output' + os.sep


def _remove_pcd_compiled_overrides(output_root: str) -> list[str]:
    """Remove PCD compiled-output files from every PCD_WORKAREA subtree.

    Walks *output_root* and removes any non-symlink file whose absolute path
    contains both a PCD_WORKAREA marker AND 'pchlp/output/' after that marker.
    These are intermediate PCD compilation artefacts that were carried over from
    the SLE model; they must be regenerated by the HSLE build.

    Both the file itself and its '.ref' companion (if present) are removed.

    Returns a list of removed paths relative to *output_root*.
    """
    removed: list[str] = []
    for dirpath, _dirs, files in os.walk(output_root):
        # Only act inside a PCD_WORKAREA subtree
        norm = dirpath if dirpath.endswith(os.sep) else dirpath + os.sep
        if _PCD_WORKAREA not in norm:
            continue

        # Locate the portion of the path after PCD_WORKAREA/
        idx = norm.find(_PCD_WORKAREA) + len(_PCD_WORKAREA)
        rel_in_workarea = norm[idx:]

        if _PCD_COMPILED_OUTPUT_MARKER not in rel_in_workarea:
            continue

        # This directory is inside a pchlp/output/ tree — remove all files here
        for name in files:
            p = os.path.join(dirpath, name)
            if os.path.islink(p):
                continue
            rel = os.path.relpath(p, output_root)
            try:
                os.unlink(p)
                removed.append(rel)
            except OSError:
                pass

    return removed
